Created CollectBall
FRCTeam3255/DemoBotV1 pull request #26
Opened 2021-11-20 22:47 UTC by KaneBarnes

Created CollectBall command and minor changes to Intake subsystem

2021-11-20 22:59 UTC, AngelaKimmy reviewed
Please map command to a button

2021-11-20 23:03 UTC, AngelaKimmy commented on src/main/java/frc/robot/commands/CollectBall.java
> +    intake.setIntakeSpeed(1.0);
We don't need to set intake speed here

2021-12-04 18:08 UTC, TaylerUva requested changes
You have crated the command but what makes it run? You must program it to run somehow.

2021-12-04 19:12 UTC, TaylerUva approved these changes

2021-12-04 19:12 UTC, merged

2021-12-04 19:12 UTC, TaylerUva commented
closed #25