Created Move Drivetrain Command
FRCTeam3255/DemoBotV1 pull request #27
Opened 2021-11-21 22:59 UTC by ACat701

Draft pull request for #16

2021-11-21 23:04 UTC, TaylerUva requested changes
Excellent job so far! Take a look at my notes and keep up the good work!

2021-11-21 23:04 UTC, TaylerUva commented on src/main/java/frc/robot/RobotContainer.java
> +  private SN_DualActionStick DriverStick = new SN_DualActionStick(RobotMap.ControllerMap.DRIVER_STICK);
We will want to use this in our command, so does anything needs to change to make that work?

2021-11-21 23:04 UTC, TaylerUva commented on src/main/java/frc/robot/commands/MoveDrivetrain.java
> +    double rotation = 1.0;
The goal is to have the speed and rotation be controlled by the joystick right? Take a guess as to how you would do that.

2021-12-04 18:03 UTC, AngelaKimmy approved these changes

2021-12-04 18:05 UTC, TaylerUva approved these changes

2021-12-04 18:05 UTC, merged