Created TurretPresets command
FRCTeam3255/DemoBotV1 pull request #31
Opened 2021-12-04 20:11 UTC by ACat701

Draft pull request for #19

2021-12-04 20:19 UTC, TaylerUva commented
blocked by #20 an #21

2021-12-04 20:20 UTC, TaylerUva commented
@ACat701 in your description you will want to say:
close #19
that way it auto closes. the keyword "closes" makes the magic happen.

2021-12-04 20:47 UTC, ACat701 commented
Closes #19

2021-12-11 03:05 UTC, TaylerUva requested changes
Excellent. Now all we need to do is a in a speed limit (don't want the thing to kill itself). We will also need to do `config_kP(0, 1)` on the motors. 

This has to do with a thing called PID (I'll explain in more detail later). Basically the reason it was not working, is for position it does some math P*x+I*y+D*z. If PID are 0 are all zero the equation equals 0. Meaning motor output is 0.

2021-12-11 16:30 UTC, TaylerUva requested changes
Please see my comments

2021-12-11 16:30 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +    return hoodMotor.getSelectedSensorPosition() / 41;
This number is being used in multiple places. What if we want to change it?

2021-12-11 16:30 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Susan.java
> +        susanMotor.set(ControlMode.Position, rotation * 85);
This number is being used in multiple places. What if we want to change it?

2021-12-11 16:30 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +    hoodMotor.set(ControlMode.Position, angle * 41);
This number is being used in multiple places. What if we want to change it?

2021-12-11 21:19 UTC, TaylerUva requested changes

2021-12-11 21:19 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Susan.java
> +        double r_rotation = rotation;
why create this extra variable?

2021-12-11 21:19 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +    double r_angle = angle;
why create this extra variable?

2021-12-11 21:19 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Hood.java
> +    hoodMotor.configPeakOutputReverse(-0.4);
Have to set k_P here

2021-12-11 22:14 UTC, TaylerUva approved these changes

2021-12-11 22:30 UTC, TaylerUva approved these changes

2021-12-11 22:30 UTC, merged

2021-12-11 22:39 UTC, TaylerUva commented
close #31

2021-12-11 22:40 UTC, TaylerUva commented
close #19